from __future__ import annotations

from django.urls import path

from .views import (
    api_alert_webhook,
    api_alertmanager_silence_create,
    api_dashboard,
    api_job_run_detail,
    api_job_run_log,
    api_job_run_log_download,
    api_job_runs,
    api_jobs,
    api_jobs_create,
    api_jobs_delete,
    api_jobs_duplicate,
    api_jobs_update,
    api_settings,
    api_settings_apply,
    api_settings_delete,
    api_settings_help_set,
    api_settings_set,
    api_users,
    api_users_create,
    api_users_delete,
    api_users_update,
    api_workers,
    index,
    job_runs,
    jobs,
    settings_page,
    users,
    workers,
)

app_name = "scheduler_ops"

urlpatterns = [
    path("", index, name="index"),
    path("workers/", workers, name="workers"),
    path("jobs/", jobs, name="jobs"),
    path("job-runs/", job_runs, name="job_runs"),
    path("settings/", settings_page, name="settings"),
    path("users/", users, name="users"),
    path("api/dashboard/", api_dashboard, name="api_dashboard"),
    path("api/alert-webhook/<str:token>/", api_alert_webhook, name="api_alert_webhook"),
    path("api/alertmanager/silence/create/", api_alertmanager_silence_create, name="api_alertmanager_silence_create"),
    path("api/workers/", api_workers, name="api_workers"),
    path("api/jobs/", api_jobs, name="api_jobs"),
    path("api/jobs/create/", api_jobs_create, name="api_jobs_create"),
    path("api/jobs/<int:job_id>/delete/", api_jobs_delete, name="api_jobs_delete"),
    path("api/jobs/<int:job_id>/duplicate/", api_jobs_duplicate, name="api_jobs_duplicate"),
    path("api/jobs/<int:job_id>/update/", api_jobs_update, name="api_jobs_update"),
    path("api/job-runs/", api_job_runs, name="api_job_runs"),
    path("api/job-runs/<int:run_id>/", api_job_run_detail, name="api_job_run_detail"),
    path("api/settings/", api_settings, name="api_settings"),
    path("api/settings/set/", api_settings_set, name="api_settings_set"),
    path("api/settings/delete/", api_settings_delete, name="api_settings_delete"),
    path("api/settings/apply/", api_settings_apply, name="api_settings_apply"),
    path("api/settings/help/set/", api_settings_help_set, name="api_settings_help_set"),
    path("api/users/", api_users, name="api_users"),
    path("api/users/create/", api_users_create, name="api_users_create"),
    path("api/users/<int:user_id>/delete/", api_users_delete, name="api_users_delete"),
    path("api/users/<int:user_id>/update/", api_users_update, name="api_users_update"),
    path("api/job-runs/<int:run_id>/log/", api_job_run_log, name="api_job_run_log"),
    path(
        "api/job-runs/<int:run_id>/log/download/",
        api_job_run_log_download,
        name="api_job_run_log_download",
    ),
]
