# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import worker_pb2 as worker__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in worker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/scheduler.v1.WorkerService/Ping',
                request_serializer=worker__pb2.PingRequest.SerializeToString,
                response_deserializer=worker__pb2.PingResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/scheduler.v1.WorkerService/GetStatus',
                request_serializer=worker__pb2.GetStatusRequest.SerializeToString,
                response_deserializer=worker__pb2.GetStatusResponse.FromString,
                _registered_method=True)
        self.StartJob = channel.unary_unary(
                '/scheduler.v1.WorkerService/StartJob',
                request_serializer=worker__pb2.StartJobRequest.SerializeToString,
                response_deserializer=worker__pb2.StartJobResponse.FromString,
                _registered_method=True)
        self.CancelJob = channel.unary_unary(
                '/scheduler.v1.WorkerService/CancelJob',
                request_serializer=worker__pb2.CancelJobRequest.SerializeToString,
                response_deserializer=worker__pb2.CancelJobResponse.FromString,
                _registered_method=True)
        self.Drain = channel.unary_unary(
                '/scheduler.v1.WorkerService/Drain',
                request_serializer=worker__pb2.DrainRequest.SerializeToString,
                response_deserializer=worker__pb2.DrainResponse.FromString,
                _registered_method=True)
        self.ReloadConfig = channel.unary_unary(
                '/scheduler.v1.WorkerService/ReloadConfig',
                request_serializer=worker__pb2.ReloadConfigRequest.SerializeToString,
                response_deserializer=worker__pb2.ReloadConfigResponse.FromString,
                _registered_method=True)
        self.ConfirmContinuation = channel.unary_unary(
                '/scheduler.v1.WorkerService/ConfirmContinuation',
                request_serializer=worker__pb2.ConfirmContinuationRequest.SerializeToString,
                response_deserializer=worker__pb2.ConfirmContinuationResponse.FromString,
                _registered_method=True)


class WorkerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Drain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReloadConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfirmContinuation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=worker__pb2.PingRequest.FromString,
                    response_serializer=worker__pb2.PingResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=worker__pb2.GetStatusRequest.FromString,
                    response_serializer=worker__pb2.GetStatusResponse.SerializeToString,
            ),
            'StartJob': grpc.unary_unary_rpc_method_handler(
                    servicer.StartJob,
                    request_deserializer=worker__pb2.StartJobRequest.FromString,
                    response_serializer=worker__pb2.StartJobResponse.SerializeToString,
            ),
            'CancelJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelJob,
                    request_deserializer=worker__pb2.CancelJobRequest.FromString,
                    response_serializer=worker__pb2.CancelJobResponse.SerializeToString,
            ),
            'Drain': grpc.unary_unary_rpc_method_handler(
                    servicer.Drain,
                    request_deserializer=worker__pb2.DrainRequest.FromString,
                    response_serializer=worker__pb2.DrainResponse.SerializeToString,
            ),
            'ReloadConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.ReloadConfig,
                    request_deserializer=worker__pb2.ReloadConfigRequest.FromString,
                    response_serializer=worker__pb2.ReloadConfigResponse.SerializeToString,
            ),
            'ConfirmContinuation': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfirmContinuation,
                    request_deserializer=worker__pb2.ConfirmContinuationRequest.FromString,
                    response_serializer=worker__pb2.ConfirmContinuationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scheduler.v1.WorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('scheduler.v1.WorkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scheduler.v1.WorkerService/Ping',
            worker__pb2.PingRequest.SerializeToString,
            worker__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scheduler.v1.WorkerService/GetStatus',
            worker__pb2.GetStatusRequest.SerializeToString,
            worker__pb2.GetStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scheduler.v1.WorkerService/StartJob',
            worker__pb2.StartJobRequest.SerializeToString,
            worker__pb2.StartJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scheduler.v1.WorkerService/CancelJob',
            worker__pb2.CancelJobRequest.SerializeToString,
            worker__pb2.CancelJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Drain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scheduler.v1.WorkerService/Drain',
            worker__pb2.DrainRequest.SerializeToString,
            worker__pb2.DrainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReloadConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scheduler.v1.WorkerService/ReloadConfig',
            worker__pb2.ReloadConfigRequest.SerializeToString,
            worker__pb2.ReloadConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfirmContinuation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scheduler.v1.WorkerService/ConfirmContinuation',
            worker__pb2.ConfirmContinuationRequest.SerializeToString,
            worker__pb2.ConfirmContinuationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
